
#ifndef ANKI_DISABLE_FFX_HALF
#define ANKI_DISABLE_FFX_HALF 0
#endif

#if ANKI_DISABLE_FFX_HALF
#define FFX_HALF 0
#else
#define FFX_HALF 1
#endif

#define FFX_GPU 1
#define FFX_GLSL 1

#define FFX_FSR2_OPTION_HDR_COLOR_INPUT 1
#define FFX_FSR2_OPTION_LOW_RESOLUTION_MOTION_VECTORS 1
#define FFX_FSR2_OPTION_JITTERED_MOTION_VECTORS 0
#define FFX_FSR2_OPTION_INVERTED_DEPTH 0
#define FFX_FSR2_OPTION_APPLY_SHARPENING 0 // Will apply Rcas later
#define FFX_FSR2_OPTION_USE_LANCZOS_LUT 1
